### ISSUE TITLE
Revise Problem Statement

### ISSUE THREAD

**Issue by janejuan** [FannieFann/Info-442-Global-Souvenir-Guidebook#1]
- Address customer pains and be more clear in the problem statement 
- Provide the evidence/ existing solutions and address why they are not good enough for this problem

**Comment by GarsonYang** [comment]
test

**Comment by janejuan** [comment]
See if you guys have questions for the revision below:
 
Seattle attracts numerous tourists every year. In the limited visiting time, tourists need to figure out what Seattle specialties are, select meaningful gifts for their friends and family, find where to buy them and search for operation hours of stores. So far, there is no one single collaborative source of information. It takes effort and time for tourists to do the research online. Existing solutions are either product-oriented or store-oriented. For instance, Yelp provides store information and shop categories but it doesn’t provide product information. Some other traveling articles have the top souvenir recommendations in Seattle. People need to cross check various  references and gather the information by themselves. This is a problem reducing their precious visiting time.
