### ISSUE TITLE
[Major] filters not woking

### ISSUE THREAD

**Issue by albertli354** [FannieFann/Info-442-Global-Souvenir-Guidebook#22]
**Bug description**
In the result page, I tried to select "books" in the filter, and the result shows Pike Place Fish Market instead of Amazon books. The filter function seems does not achieve what I want. 

**To reproduce**
1. Go to the homepage.
2. click the mark.
3. click "books" under product type.
4. The result page showing "Pike Place Fish Market"

**Expected Behavior**
The filter result show corresponding to the label users selected 

![image](https://user-images.githubusercontent.com/26781751/70285676-2ce86500-177d-11ea-944f-a9bfe931ad9b.png)

**Comment by FannieFann** [comment]
That is because in our database, Amazon Books do not have book product.. We will add this product afterwards.

Thanks:)

**Comment by deepforce** [comment]
fix #41
