### ISSUE TITLE
[MINOR] Images are stretched

### ISSUE THREAD

**Issue by thebriando** [FannieFann/Info-442-Global-Souvenir-Guidebook#23]
http://52.183.24.181:3000/view1

Images on results are stretched. They do not match the user-uploaded picture. 

![image](https://user-images.githubusercontent.com/18522836/70286285-7934a480-177f-11ea-9fcd-bad2100ae88f.png)
![image](https://user-images.githubusercontent.com/18522836/70286313-923d5580-177f-11ea-851b-9532c72dfe2a.png)

**Comment by deepforce** [comment]
Because we set the images size fixed.

**Comment by deepforce** [comment]
fixed #41
