### ISSUE TITLE
[minor]

### ISSUE THREAD

**Issue by anantr98** [FannieFann/Info-442-Global-Souvenir-Guidebook#24]
You can filter by price even when the user hasn't picked a product that they want to buy. It's unclear what the filter is for (average price of products at the store?). You can reproduce this by clicking on Seattle on the map and then clicking filter from "Low to High" or "High to Low". Not a major issue but more of just a specification issue

**Comment by janejuan** [comment]
The price is based on the store level which is similar to the Yelp concept. We provide only some major selected products. Thank you
