### ISSUE TITLE
[Major] opening a specific business in a new tab gives an error

### ISSUE THREAD

**Issue by ssunni12** [FannieFann/Info-442-Global-Souvenir-Guidebook#25]
Right clicking on the "details" button on a listing for a business is supposed to open the details in a new tab, but instead it just gives a 'Cannot read property 'id' of undefined' error.

**Comment by FannieFann** [comment]
Could you give us a screenshot of the error and the name of business? Please add more details for this bug so we can observe it.

**Comment by ssunni12** [comment]
![error](https://user-images.githubusercontent.com/43485485/70287284-3aa0e900-1783-11ea-98ac-83959d9c5385.PNG)
Here is a screenshot of the error, it occurs for any business I try to right click and open details in a new tab.

**Comment by deepforce** [comment]
Thank you. This is a Major issue for our system. It should pass the storeid parameter with Link.

**Comment by 3ickey** [comment]
I agree that this is a major bug. Especially when you think about how people shop online. People tend to save an item of interest in a new tab and keep shopping.
