### ISSUE TITLE
[minor] Clicking on an image doesn't go anywhere

### ISSUE THREAD

**Issue by anantr98** [FannieFann/Info-442-Global-Souvenir-Guidebook#26]
The images of all the stores that exist in Seattle are hyperlinked but when you click on it, even when filtered, it refreshes and ignores the filter that you set on it. For example, when you click "toys" on the left side filtering menu and then click on the picture of "Fireworks Gallery" as the store that pops up, it refreshes the entire page.

**Comment by janejuan** [comment]
Thank you for your finding. We didn't plan to shift the website via the photo. This is expected. There is the website visit us down in the store information. You can visit the website through that hyperlink.
