### ISSUE TITLE
[Minor] Hit enter key not working for search bar

### ISSUE THREAD

**Issue by albertli354** [FannieFann/Info-442-Global-Souvenir-Guidebook#27]
**Bug description**
When I hit the enter key on my keyboard for search bar, the website not searching for anything. I think most users expected to use the "enter" key on their keyboard to accomplish the search task.

**To reproduce**
1. Open the homepage. 
2. hit the mark on the map.
3. Enter something in the search bar.
4. Hit "enter" key on the keyboard.
5. No searching behavior.

**Expected behavior**
When users hit enter in the search bar after entering something, the website should return the search result.
![image](https://user-images.githubusercontent.com/26781751/70286802-6ae78800-1781-11ea-8109-139a6a7e3790.png)

**Comment by deepforce** [comment]
Yes, maybe it's good to add this in the future.
