### ISSUE TITLE
[Minor] Filtering a list by price and then clicking an image just refreshed the list to default

### ISSUE THREAD

**Issue by ssunni12** [FannieFann/Info-442-Global-Souvenir-Guidebook#28]
If you click 'Price: High To Low' with no other filters on the list at all and then click on the image for a business, the list will refresh and go back to the 'default' setting of the list. It also will erase any filters set for it; I had 'accessories' checked in the filters menu while in the 'default' setting, then clicked  'Price: High To Low,' then clicked on the image for a business, and it refreshed back to the 'default' setting with no filters set at all ('accessories' was not selected).

**Comment by deepforce** [comment]
This is a feature should be implemented for user friendly.

**Comment by deepforce** [comment]
fix #41
