### ISSUE TITLE
Clicking on Images don't link to content/refresh the page [Major]

### ISSUE THREAD

**Issue by CD6-timury** [FannieFann/Info-442-Global-Souvenir-Guidebook#29]
**Describe the bug**
Clicking on the images in result page doesn't redirect to the page of the result, but it rather refreshes the current page.

**To Reproduce**
1. Click on "Seattle Marker" on the map.
2. Click on image
3. See error

**Expected behavior**
Clicking on the image should take to the result page as if you pressed "Details" button.

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.1)
 - Browser Chrome (Version 78.0.3904.108 64 Bit)

**Comment by deepforce** [comment]
**Not a Major Problem**
This is because I didn't expect users would click on the image for redirection. But it's a good idea to add    it.
