### ISSUE TITLE
[MINOR] Search filtering options misaligned on smaller browser size.

### ISSUE THREAD

**Issue by tfpenner** [FannieFann/Info-442-Global-Souvenir-Guidebook#31]
Describe the bug
The search filtering inputs are misaligned on a smaller browser. 

To Reproduce
     1. Click on the red mark on the map for Seattle to be directed to the search page
     2. Shrink the width of the web browser
     3. Look at the form inputs and their different locations

Expected behavior
I expected the inputs to be organized in a way that was intuitive for a smaller browser. It was hard to initially know where the price range filter went when I shrunk the page.

Screenshots
<img width="474" alt="Screen Shot 2019-12-05 at 5 53 16 PM" src="https://user-images.githubusercontent.com/53621324/70289137-b2bddd80-1788-11ea-8e79-4a6d2a5199d3.png">

Additional context
Using Google Chrome on a MacBook Pro

**Comment by deepforce** [comment]
Responsive Web Design Problem.

**Comment by FannieFann** [comment]
We did lots of attempts while seems not working very well based on the current webpage design. Time is limited to do some revisions on the whole page architecture. Thus, we decided not to refine this minor problem.
