### ISSUE TITLE
[Minor] Search in the next page returns no result

### ISSUE THREAD

**Issue by LeoKwo** [FannieFann/Info-442-Global-Souvenir-Guidebook#36]
**Describe the bug**
Searching after clicking the 'next page' button returns no result.

**To Reproduce**
1. Scroll to the very bottom of the result page
2. Click on 'Next' to go to the next page
3. Type and search "Amazon"
4. Receive no result

**Expected behavior**
Amazon is the first store and searching Amazon on the first page would give the desired outcome. But searching on the second page returns no result.

**Screenshots**
First Page:
![Screen Shot 2019-12-07 at 16 16 45](https://user-images.githubusercontent.com/37886365/70382201-f8a3ae80-190c-11ea-87a2-c11e74114671.jpg)
Second Page:
![Screen Shot 2019-12-07 at 16 17 06](https://user-images.githubusercontent.com/37886365/70382207-05c09d80-190d-11ea-81be-a2d5d0171475.jpg)

**System**
macOS 10.15.1
Chrome version 78.0.3904.108

**Comment by deepforce** [comment]
Same as #34
