### ISSUE TITLE
[minor] there's no results for seniors

### ISSUE THREAD

**Issue by anthonyqcn** [FannieFann/Info-442-Global-Souvenir-Guidebook#37]
**Describe the bug**
This is more of a content issue than a technical bug, but it poses significant usability issues when I try to look for gifts for seniors when there actually are 0 stores I can go to to shop for seniors. 

**To Reproduce**

- Go to 'http://52.183.24.181:3000/'
- Click on the maps pin over Seattle
- Click on the check box next to 'Seniors' under 'For Whom'
- Error occurs here: no results are displayed

**Expected behavior**
I expected at least one store to come up in the results list when attempting to shop for seniors.

**Comment by deepforce** [comment]
Data issue

**Comment by deepforce** [comment]
Sorry, typo issue. It should be 'Senior' not 'Seniors'.
