### ISSUE TITLE
[MINOR]  A reset button for filter in the resultsPage

### ISSUE THREAD

**Issue by lyuyueCC** [FannieFann/Info-442-Global-Souvenir-Guidebook#38]
- Description of the failure:
A reset button for filter in the resultsPage is missing.
 - Reproduction steps:
Go to the home page and click on the marker in the map.
Select all the categories that the user wants.
Expected results is presented.
While the user want to start a brand new filtering search, he might have to spend quite a lot time on unbutton the current selections one by one. 
 - Clear rationale:
There are over ten catogories in your filter in the resultsPage, sometimes users might want to unselect them all to start all over. Having each one unselected mannually would take lots of time and work. Therefore, I suggest you having a result button there. This is not a must, but would definitely improve user experiences.

**Comment by deepforce** [comment]
Might be something not perfect but it can improve in the future.

**Comment by deepforce** [comment]
After discussion, we think there is no need for this feature since users can refresh the page for reset
