### ISSUE TITLE
[minor] favicon and website name are generic React App

### ISSUE THREAD

**Issue by Uyedacb** [FannieFann/Info-442-Global-Souvenir-Guidebook#39]
**Describe the bug**
The favicon and the displayed website name in the tab section of the browser are the generic react icon and name.

**Expected Behavior**
Expected the icon/browser name to be relevant to the website content.

**Screenshots**
![image](https://user-images.githubusercontent.com/24310183/70475529-8ad0c180-1a89-11ea-95d7-8e6034eb2039.png)

**Desktop:**
OS: Windows 10
Browser Chrome
Version 78.0.3904.108 (64 bit)

**Comment by deepforce** [comment]
lol. I think I have to find a different one to replace it.
