### ISSUE TITLE
[minor] leaked logs inside of developer console

### ISSUE THREAD

**Issue by Uyedacb** [FannieFann/Info-442-Global-Souvenir-Guidebook#40]
**Describe the minor issue**
Console leaks data when clicking on different filtering options.

**To Reproduce**
1. Go to http://52.183.24.181:3000/view1
2. Open developer console
3. Click on "Kitchen Accessory", "Book", or "Toy"
4. See API request, Boolean statements, and object logged inside of console

**Expected behavior**
Nothing sensitive to be logged inside of the developer console.

**Screenshots**
![image](https://user-images.githubusercontent.com/24310183/70476056-c6b85680-1a8a-11ea-8d9b-253234a0c21b.png)

**Device Used:**
OS: Windows 10
Browser: Chrome
Version: 78.0.3904.108 (64 bit)

**Comment by deepforce** [comment]
Finally, someone find this! Good job!

**Comment by deepforce** [comment]
fix #41
