### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by amoghdave** [FannieFann/Info-442-Global-Souvenir-Guidebook#48]
Description:
The search bar is not functional. I search for "books" and the view of the website doesn't get updated. It still just shows the original layout and includes Boeing store which doesn't sell books. 

Steps to recreate:
- Go to the homepage
- click on the search bar and search for anything ie "books"
- the view and the list of the stores do not change 
-- also click on any of the check boxes on the side, none of them affect the view either. 

intended behavior:
after searching for books, all the stores that contain the keyword books should be the only ones that show up in the view. Clicking on the check boxes on the side don't filter the view either. that view is broken. 

OS: MacOS
Browser: Safari

**Comment by deepforce** [comment]
**Not A Issue**
We shutdown our backend server and frontend server these days for maintenance. Maybe that's the reason why it happened.
